refactor(git hooks): remove post commit and check all on pre commit

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,25 +1,37 @@
 #!/bin/sh
 
-HAS_ISSUES=0
-FIRST_FILE=1
+check_char='\xE2\x9C\x93'
+cross_char='\xE2\x9D\x8C'
+green='\033[0;32m'
+red='\033[031m'
+nc='\033[0m'
+check="$green$check_char$nc"
+error="$red$cross_char$nc"
 
-echo -e -n "Formatting edited files...\n"
 
-for file in $(git diff --name-only --staged); do
-    FMT_RESULT="$(rustfmt --skip-children --force --write-mode diff $file 2>/dev/null || true)"
-    if [ "$FMT_RESULT" != "" ]; then
-        if [ $FIRST_FILE -eq 0 ]; then
-            echo -e -n ", "
-        fi  
-        echo -e -n "$file"
-        HAS_ISSUES=1
-        FIRST_FILE=0
-    fi
-done
-
-if [ $HAS_ISSUES -eq 0 ]; then
-    exit 0
+echo -e -n "Checking formatting code...\n"
+cargo fmt --all -- --check
+if [[ $? -ne 0 ]]; then
+    echo -e -n "$error Bad format\n"
+    exit 1
+else
+    echo -e -n "$check Nice format\n"
 fi
 
-echo ". Your code has formatting issues in files listed above. Format your code with \`make format\` or call rustfmt manually.\n"
-exit 1
+echo -e -n "Checking code...\n"
+cargo clippy -- -D warnings
+if [[ $? -ne 0 ]]; then
+    echo -e -n "$error Bad code\n"
+    exit 1
+else
+    echo -e -n "$check Nice code\n"
+fi
+
+echo -e -n "Running tests... \n"
+cargo test --color always
+if [[ $? -ne 0 ]]; then
+    echo -e -n "$error Test failed\n"
+    exit 1
+else
+    echo -e -n "$check Nice tests\n"
+fi
